### ISSUE TITLE
How can I set up the bot?

### ISSUE THREAD

**Issue by magicstone1412** [sashgorokhov/telegram-reddit-newsbot#1]
Could you please guide me how to set up the bot on Heroku? I am not an IT engineer.

I wanna get the new post from a subreddit and forward to Telegram. Thank you

**Comment by sashgorokhov** [comment]
Hi @magicstone1412! Heroku has a comprehensive tutorial about deploying python projects on it - https://devcenter.heroku.com/articles/getting-started-with-python#introduction

This project is currently in alpha and I am only the user of it. I havent written any documentation yet. I'll do that these weekends, maybe
